### ISSUE TITLE
bestandsnaam met factuurnummer

### ISSUE THREAD

**Issue by NadiaCurinckx** [KodeFoxx-Projects/Kostenverdeling#1]

**Comment by aredfox** [comment]
Ok, maar nog niet in nama van de map. @NadiaCurinckx - hier moeten we even naar kijken. Is de factuurnummer altijd dezelfde, ongeact de vzw's in het bestand? Indien ja, dan kan ik dit nog aanpassen en moet je niet per VZW het factuurnummer invullen, maar kan je dit doen voor alle.

**Comment by aredfox** [comment]
Ok for Milestone:20171120 - *maar* mee te nemen naar volgende release.
